# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b86437741b5a38f3ac2b8e9aa4af2834748e9253e615e092aedde4a09ffd586162986fc2600427784c6d222efbb02ef99d53de3dd438094df6264e4214764e

test:
  secret_key_base: 0bd16991dc57b894761d403b915cdf452e7bb9f4d90074b184f351a334de209a536af964f15dcd61734877fb14781a8541888e48de3cdad6dce7f532e11ee920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
